-- PostgreSQL 16 domain schema for ООО "МебельОрг".
-- Django migrations remain the authoritative application schema and also
-- create framework tables for permissions, sessions, and administration.

BEGIN;

CREATE TABLE furniture_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(20) NOT NULL UNIQUE
        CHECK (code IN ('admin', 'manager', 'client')),
    name varchar(80) NOT NULL UNIQUE
);

CREATE TABLE furniture_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password varchar(128) NOT NULL,
    last_login timestamptz,
    is_superuser boolean NOT NULL DEFAULT false,
    username varchar(150) NOT NULL UNIQUE,
    first_name varchar(150) NOT NULL DEFAULT '',
    last_name varchar(150) NOT NULL DEFAULT '',
    email varchar(254) NOT NULL DEFAULT '',
    is_staff boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    date_joined timestamptz NOT NULL DEFAULT now(),
    full_name varchar(255) NOT NULL,
    role_id bigint REFERENCES furniture_role(id) ON DELETE RESTRICT
);

CREATE TABLE furniture_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE furniture_supplier (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE furniture_manufacturer (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE furniture_unit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE furniture_product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article varchar(30) NOT NULL UNIQUE,
    name varchar(500) NOT NULL,
    price numeric(12, 2) NOT NULL CHECK (price >= 0),
    discount numeric(5, 2) NOT NULL DEFAULT 0
        CHECK (discount >= 0 AND discount <= 100),
    stock_quantity integer NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    description text NOT NULL DEFAULT '',
    image varchar(100) NOT NULL DEFAULT '',
    category_id bigint NOT NULL REFERENCES furniture_category(id) ON DELETE RESTRICT,
    manufacturer_id bigint NOT NULL REFERENCES furniture_manufacturer(id) ON DELETE RESTRICT,
    supplier_id bigint NOT NULL REFERENCES furniture_supplier(id) ON DELETE RESTRICT,
    unit_id bigint NOT NULL REFERENCES furniture_unit(id) ON DELETE RESTRICT
);

CREATE TABLE furniture_pickuppoint (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address varchar(500) NOT NULL UNIQUE
);

CREATE TABLE furniture_orderstatus (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE furniture_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date date NOT NULL,
    delivery_date date NOT NULL,
    pickup_code integer NOT NULL UNIQUE CHECK (pickup_code >= 0),
    customer_id bigint NOT NULL REFERENCES furniture_user(id) ON DELETE RESTRICT,
    pickup_point_id bigint NOT NULL REFERENCES furniture_pickuppoint(id) ON DELETE RESTRICT,
    status_id bigint NOT NULL REFERENCES furniture_orderstatus(id) ON DELETE RESTRICT
);

CREATE TABLE furniture_orderitem (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity integer NOT NULL CHECK (quantity >= 1),
    order_id bigint NOT NULL REFERENCES furniture_order(id) ON DELETE CASCADE,
    product_id bigint NOT NULL REFERENCES furniture_product(id) ON DELETE RESTRICT,
    CONSTRAINT unique_product_in_order UNIQUE (order_id, product_id)
);

CREATE INDEX furniture_user_role_idx ON furniture_user(role_id);
CREATE INDEX furniture_product_category_idx ON furniture_product(category_id);
CREATE INDEX furniture_product_supplier_idx ON furniture_product(supplier_id);
CREATE INDEX furniture_product_manufacturer_idx ON furniture_product(manufacturer_id);
CREATE INDEX furniture_order_customer_idx ON furniture_order(customer_id);
CREATE INDEX furniture_order_status_idx ON furniture_order(status_id);
CREATE INDEX furniture_orderitem_product_idx ON furniture_orderitem(product_id);

COMMIT;

